BookShop/BookShop.Mvc/Models/Book.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BookShop.Mvc.Models
{
    public class Book
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Author { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        [Range(0d, double.MaxValue)]
        public decimal Price { get; set; }

        public List<OrderLine> OrderLines { get; set; }
    }
}

BookShop/BookShop.Mvc/Models/DatabaseContext.cs
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace BookShop.Mvc.Models
{
    public class DatabaseContext
        : DbContext, IDatabaseContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseInMemoryDatabase("Bookshop");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<OrderLine>()
                .HasKey(ol => new {ol.BookId, ol.OrderId});


            //Seed Data
            var books = new List<Book>
            {
                new Book { Id = 1, Author = "Gojko Adzic", Title = "Bridging the Communication Gap", Price = 12.20M },
                new Book { Id = 2, Author = "Gojko Adzic", Title = "Specification By Example", Price = 15.30M },
                new Book { Id = 3, Author = "Lisa Crispin and Janet Gregory", Title = "Agile Testing", Price = 20.20M },
                new Book { Id = 4, Author = "Mitch Lacey", Title = "The Scrum Field Guide", Price = 15.31M },
                new Book { Id = 5, Author = "Martin Fowler", Title = "Refactoring", Price = 29.55M },
                new Book { Id = 6, Author = "Esther Derby and Diana Larsen", Title = "Agile Retrospectives", Price = 16.99M },
                new Book { Id = 7, Author = "Matt Wynne and Aslak Hellesoy", Title = "The Cucumber Book", Price = 18.00M },
                new Book { Id = 8, Author = "David Chelimsky", Title = "The RSpec Book", Price = 17.50M }
            };

            foreach (var book in books)
            {
                modelBuilder.Entity<Book>().HasData(book);
            }
        }

        public DbSet<Order> Orders { get; set; }

        public DbSet<Book> Books { get; set; }

        public DbSet<OrderLine> OrderLines { get; set; }
    }
}

BookShop/BookShop.Mvc/Models/EditArguments.cs
using System.ComponentModel.DataAnnotations;

namespace BookShop.Mvc.Models
{
    public class EditArguments
    {
        public int BookId { get; set; }

        [Range(0, int.MaxValue)]
        public int Quantity { get; set; }
    }
}

BookShop/BookShop.Mvc/Models/ErrorViewModel.cs
namespace BookShop.Mvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BookShop/BookShop.Mvc/Models/IDatabaseContext.cs
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace BookShop.Mvc.Models
{
    public interface IDatabaseContext : IDisposable
    {
        DbSet<Order> Orders { get; set; }
        DbSet<Book> Books { get; set; }
        DbSet<OrderLine> OrderLines { get; set; }
        DatabaseFacade Database { get; }
        int SaveChanges();
    }
}

BookShop/BookShop.Mvc/Models/Order.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace BookShop.Mvc.Models
{
    public class Order
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Status { get; set; }

        [Required]
        public decimal Price => OrderLines.Sum(ol => ol.Price);

        public List<OrderLine> OrderLines { get; set; }
    }
}

BookShop/BookShop.Mvc/Models/OrderLine.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BookShop.Mvc.Models
{
    public class OrderLine
    {
        public virtual Book Book { get; set; }

        [Required]
        [ForeignKey(nameof(Models.Book))]
        [Column(Order = 0)]
        public int BookId { get; set; }

        public virtual Order Order { get; set; }

        [Required]
        [ForeignKey(nameof(Models.Order))]
        [Column(Order = 1)]
        public int OrderId { get; set; }

        [Range(1, int.MaxValue)]
        [Required]
        public int Quantity { get; set; }

        public decimal Price => Quantity * Book.Price;
    }
}

BookShop/BookShop.Mvc/Models/ShoppingCart.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;

namespace BookShop.Mvc.Models
{
    public class ShoppingCart
    {
        private readonly List<OrderLine> _orderLines = new List<OrderLine>();

        [DisplayName("Total Price")]
        public decimal Price => _orderLines.Sum(li => li.Price);

        public int Count => _orderLines.Sum(li => li.Quantity);

        public IEnumerable<OrderLine> Lines => _orderLines;

        public void AddLineItem(OrderLine lineItem)
        {
            _orderLines.Add(lineItem);
        }

        public void RemoveLineItem(int bookId)
        {
            _orderLines.Remove(_orderLines.FirstOrDefault(li => li.Book.Id == bookId));
        }
    }
}

BookShop/BookShop.Mvc/Controllers/CatalogController.cs
using BookShop.Mvc.Logic;
using Microsoft.AspNetCore.Mvc;

namespace BookShop.Mvc.Controllers
{
    public class CatalogController : Controller
    {
        private readonly IBookLogic _bookLogic;

        public CatalogController(IBookLogic bookLogic)
        {
            _bookLogic = bookLogic;
        }

        public ActionResult Search(string searchTerm)
        {
            var books =  _bookLogic.Search(searchTerm);

            return View("List", books);
        }

       

        public ActionResult Details(int id)
        {
            var book = _bookLogic.GetBookById(id);
            return View(book);
        }

        
    }
}

BookShop/BookShop.Mvc/Controllers/HomeController.cs
using BookShop.Mvc.Logic;
using Microsoft.AspNetCore.Mvc;

namespace BookShop.Mvc.Controllers
{
    public class HomeController
        : Controller
    {
        private readonly IBookLogic _bookLogic;

        public HomeController(IBookLogic bookLogic)
        {
            _bookLogic = bookLogic;
        }

        public ActionResult Index()
        {
            var cheapBooks = _bookLogic.FindCheapBooks(3);
            return View(cheapBooks);
        }

        public ActionResult Privacy()
        {
            return View();
        }
    }
}

BookShop/BookShop.Mvc/Controllers/ShoppingCartController.cs
using BookShop.Mvc.Logic;
using BookShop.Mvc.Models;
using Microsoft.AspNetCore.Mvc;

namespace BookShop.Mvc.Controllers
{
    public class ShoppingCartController
        : Controller
    {
        private readonly IDatabaseContext _databaseContext;
        private readonly IShoppingCartLogic _shoppingCartLogic;


        public ShoppingCartController(IDatabaseContext databaseContext, IShoppingCartLogic shoppingCartLogic)
        {
            _databaseContext = databaseContext;
            _shoppingCartLogic = shoppingCartLogic;
        }

        public ActionResult Index()
        {
            var shoppingCart = _shoppingCartLogic.GetShoppingCart(HttpContext.Session);
            return View(shoppingCart);
        }

        public ActionResult Add(int bookId)
        {
            var shoppingCart = _shoppingCartLogic.GetShoppingCart(HttpContext.Session);

            ViewData.Model = _shoppingCartLogic.AddBookToCart(HttpContext.Session,bookId, shoppingCart);
            return RedirectToAction(nameof(Index));
        }

       

        [HttpGet]
        public ActionResult DeleteItem(int id)
        {
            ViewData.Model = _shoppingCartLogic.RemoveBookFromCart(HttpContext.Session, id);
            return RedirectToAction("Index");
        }

        

        [HttpPost]
        //[ValidateInput(true)]
        public ActionResult Edit(EditArguments editArgs)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index");
            }

            _shoppingCartLogic.EditBookInCart(HttpContext.Session, editArgs);

            return RedirectToAction("Index");
        }

        


        
    }
}

BookShop/BookShop.Mvc/Views/Catalog/Details.cshtml
@using BookShop.Mvc.Models

@model Book

@{
    ViewBag.Title = $"{Model.Title}";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="page-header">@Model.Title <small>by @Model.Author</small></h1>

<dl class="dl-horizontal">
    <dt>Title</dt>
    <dd id="title">@Model.Title</dd>

    <dt>Author(s)</dt>
    <dd id="author">@Model.Author</dd>

    <dt>Price</dt>
    <dd id="price">&euro; @Model.Price.ToString("0.00")</dd>

    <dt>Id</dt>
    <dd id="id">@Model.Id</dd>
</dl>

@Html.ActionLink("Add to cart", "Add", "ShoppingCart", new { bookId = Model.Id }, new { @class = "btn btn-primary" })

BookShop/BookShop.Mvc/Views/Catalog/List.cshtml
@using BookShop.Mvc.Models
@model IEnumerable<Book>

@{
    ViewBag.Title = "Books";
}

<div class="jumbotron">
    <h1>Books</h1>
</div>

<div class="table-responsive">
    <table class="table table-striped" id="searchResultTable">
        <thead>
            <tr>
                <th><em>Title</em></th>
                <th><em>Author</em></th>
                <th><em>Price</em></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var book in Model)
            {
                <tr>
                    <td class="title"><h4>@Html.ActionLink(book.Title, "Details", "Catalog", new { id = book.Id }, new { })</h4></td>
                    <td class="author">@book.Author</td>
                    <td class="price">&euro; @book.Price.ToString("0.00")</td>
                    <td>@Html.ActionLink("Add to cart", "Add", "ShoppingCart", new { bookId = book.Id }, new { @class = "btn btn-primary" })</td>
                </tr>
            }
        </tbody>
    </table>
</div>

BookShop/BookShop.Mvc/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

BookShop/BookShop.Mvc/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

BookShop/BookShop.Mvc/Views/Home/Index.cshtml
@using BookShop.Mvc.Models

@model IEnumerable<Book>

@{
    ViewBag.Title = "Home";
}

<div class="jumbotron">
    <h1 class="page-header">Bookshop</h1>
    <p class="lead">The bookshop example demonstrates using SpecFlow with Selenium-based UI tests.</p>
    <p><a href="http://specflow.org/" class="btn btn-primary btn-lg" target="_blank">Learn more &raquo;</a></p>
</div>

<form class="form-group" asp-controller="Catalog" asp-action="Search" id="searchForm">
    <input type="search" id="searchTerm" name="searchTerm" class="form-control" style="display: inline-block; width: 150px;"/>
    <button type="submit" class="btn" style="font-size: 1.3em">&#9906;</button>
</form>    

<h2>Best offers</h2>

<div class="table-responsive">
    <table class="table table-striped">
        <caption>
            @Html.ActionLink("View all offers", "Search", "Catalog", new {}, new {@class = "btn btn-default"})
        </caption>
        <thead>
        <tr>
            <th><em>Title</em></th>
            <th><em>Author</em></th>
            <th><em>Price</em></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach (var book in Model)
        {
            <tr>
                <td class="title"><h4>@Html.ActionLink(book.Title, "Details", "Catalog", new { id = book.Id }, new { })</h4></td>
                <td class="author">@book.Author</td>
                <td class="price">&euro; @book.Price.ToString("0.00")</td>
                <td>@Html.ActionLink("Add to cart", "Add", "ShoppingCart", new { bookId = book.Id }, new { @class = "btn btn-primary" })</td>
            </tr>
        }
        </tbody>
    </table>
</div>

BookShop/BookShop.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookShop.Mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookShop.Mvc</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <p>&copy; @DateTime.Now.Year - The SpecFlow Team</p>
            <p><a href="http://www.specflow.org" target="_blank">SpecFlow</a> - Pragmatic BDD for .NET</p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

BookShop/BookShop.Mvc/Views/ShoppingCart/Index.cshtml
@using System.Linq
@using BookShop.Mvc.Controllers
@using BookShop.Mvc.Models;
@using Microsoft.AspNetCore.Routing
@using Microsoft.EntityFrameworkCore.Internal
@using Microsoft.Extensions.Configuration.CommandLine

@model ShoppingCart

@{
    ViewBag.Title = "Shopping Cart";
}

<h2>Shopping Cart</h2>

<div class="table-responsive">
    <table class="table table-striped">
        <thead>
        <tr>
            <th><em>Title</em></th>
            <th><em>Author</em></th>
            <th><em>Quantity</em></th>
            <th><em>Price</em></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach (var orderLine in Model.Lines)
        {
            <tr>
                <td class="title"><h4>@Html.ActionLink(orderLine.Book.Title, "Details", "Catalog", new { id = orderLine.Book.Id }, new { })</h4></td>
                <td class="author">@orderLine.Book.Author</td>
                <td>
                    @using (Html.BeginForm("Edit", "ShoppingCart", FormMethod.Post))
                    {

                        @Html.Hidden("BookId", orderLine.BookId, new { })
                        <input name="Quantity" type="number" value="@orderLine.Quantity" min="0" max="@int.MaxValue" required/>

                        <button type="submit" class="btn btn-success">&#10003;</button>
                    }
                </td>
                <td class="price">&euro; @orderLine.Price.ToString("0.00")</td>
                <td>
                    @Html.ActionLink("X", "DeleteItem", "ShoppingCart", new { id = orderLine.Book.Id }, new { @class = "btn btn-danger" })
                </td>
            </tr>
        }
        </tbody>
        <tfoot>
        <tr>
            <th><h4><strong>Total</strong></h4></th>
            <th></th>
            <th class="shoppingcart_count">@Model.Count</th>
            <th class="shoppingcart_total_amount">&euro; @Model.Price.ToString("0.00")</th>
        </tr>
        </tfoot>
    </table>
</div>